import assert from "node:assert";
import Ergast from "../src/index.js";
import test from "node:test";

const api = new Ergast({});
test("Get driver information", async () => {
	assert.deepStrictEqual(await api.drivers.get("alonso"), {
		driverId: "alonso",
		permanentNumber: 14,
		code: "ALO",
		url: "http://en.wikipedia.org/wiki/Fernando_Alonso",
		givenName: "Fernando",
		familyName: "Alonso",
		dateOfBirth: new Date("1981-07-29T00:00:00.000Z"),
		nationality: "Spanish",
	});
});
test("Get driver list", async () => {
	assert.deepStrictEqual(await api.drivers.getAll(2023, 2), [
		{
			driverId: "albon",
			permanentNumber: 23,
			code: "ALB",
			url: "http://en.wikipedia.org/wiki/Alexander_Albon",
			givenName: "Alexander",
			familyName: "Albon",
			dateOfBirth: new Date("1996-03-23T00:00:00.000Z"),
			nationality: "Thai",
		},
		{
			driverId: "alonso",
			permanentNumber: 14,
			code: "ALO",
			url: "http://en.wikipedia.org/wiki/Fernando_Alonso",
			givenName: "Fernando",
			familyName: "Alonso",
			dateOfBirth: new Date("1981-07-29T00:00:00.000Z"),
			nationality: "Spanish",
		},
		{
			driverId: "bottas",
			permanentNumber: 77,
			code: "BOT",
			url: "http://en.wikipedia.org/wiki/Valtteri_Bottas",
			givenName: "Valtteri",
			familyName: "Bottas",
			dateOfBirth: new Date("1989-08-28T00:00:00.000Z"),
			nationality: "Finnish",
		},
		{
			driverId: "de_vries",
			permanentNumber: 21,
			code: "DEV",
			url: "http://en.wikipedia.org/wiki/Nyck_de_Vries",
			givenName: "Nyck",
			familyName: "de Vries",
			dateOfBirth: new Date("1995-02-06T00:00:00.000Z"),
			nationality: "Dutch",
		},
		{
			driverId: "gasly",
			permanentNumber: 10,
			code: "GAS",
			url: "http://en.wikipedia.org/wiki/Pierre_Gasly",
			givenName: "Pierre",
			familyName: "Gasly",
			dateOfBirth: new Date("1996-02-07T00:00:00.000Z"),
			nationality: "French",
		},
		{
			driverId: "hamilton",
			permanentNumber: 44,
			code: "HAM",
			url: "http://en.wikipedia.org/wiki/Lewis_Hamilton",
			givenName: "Lewis",
			familyName: "Hamilton",
			dateOfBirth: new Date("1985-01-07T00:00:00.000Z"),
			nationality: "British",
		},
		{
			driverId: "hulkenberg",
			permanentNumber: 27,
			code: "HUL",
			url: "http://en.wikipedia.org/wiki/Nico_H%C3%BClkenberg",
			givenName: "Nico",
			familyName: "Hülkenberg",
			dateOfBirth: new Date("1987-08-19T00:00:00.000Z"),
			nationality: "German",
		},
		{
			driverId: "leclerc",
			permanentNumber: 16,
			code: "LEC",
			url: "http://en.wikipedia.org/wiki/Charles_Leclerc",
			givenName: "Charles",
			familyName: "Leclerc",
			dateOfBirth: new Date("1997-10-16T00:00:00.000Z"),
			nationality: "Monegasque",
		},
		{
			driverId: "kevin_magnussen",
			permanentNumber: 20,
			code: "MAG",
			url: "http://en.wikipedia.org/wiki/Kevin_Magnussen",
			givenName: "Kevin",
			familyName: "Magnussen",
			dateOfBirth: new Date("1992-10-05T00:00:00.000Z"),
			nationality: "Danish",
		},
		{
			driverId: "norris",
			permanentNumber: 4,
			code: "NOR",
			url: "http://en.wikipedia.org/wiki/Lando_Norris",
			givenName: "Lando",
			familyName: "Norris",
			dateOfBirth: new Date("1999-11-13T00:00:00.000Z"),
			nationality: "British",
		},
		{
			driverId: "ocon",
			permanentNumber: 31,
			code: "OCO",
			url: "http://en.wikipedia.org/wiki/Esteban_Ocon",
			givenName: "Esteban",
			familyName: "Ocon",
			dateOfBirth: new Date("1996-09-17T00:00:00.000Z"),
			nationality: "French",
		},
		{
			driverId: "perez",
			permanentNumber: 11,
			code: "PER",
			url: "http://en.wikipedia.org/wiki/Sergio_P%C3%A9rez",
			givenName: "Sergio",
			familyName: "Pérez",
			dateOfBirth: new Date("1990-01-26T00:00:00.000Z"),
			nationality: "Mexican",
		},
		{
			driverId: "piastri",
			permanentNumber: 81,
			code: "PIA",
			url: "http://en.wikipedia.org/wiki/Oscar_Piastri",
			givenName: "Oscar",
			familyName: "Piastri",
			dateOfBirth: new Date("2001-04-06T00:00:00.000Z"),
			nationality: "Australian",
		},
		{
			driverId: "russell",
			permanentNumber: 63,
			code: "RUS",
			url: "http://en.wikipedia.org/wiki/George_Russell_%28racing_driver%29",
			givenName: "George",
			familyName: "Russell",
			dateOfBirth: new Date("1998-02-15T00:00:00.000Z"),
			nationality: "British",
		},
		{
			driverId: "sainz",
			permanentNumber: 55,
			code: "SAI",
			url: "http://en.wikipedia.org/wiki/Carlos_Sainz_Jr.",
			givenName: "Carlos",
			familyName: "Sainz",
			dateOfBirth: new Date("1994-09-01T00:00:00.000Z"),
			nationality: "Spanish",
		},
		{
			driverId: "sargeant",
			permanentNumber: 2,
			code: "SAR",
			url: "http://en.wikipedia.org/wiki/Logan_Sargeant",
			givenName: "Logan",
			familyName: "Sargeant",
			dateOfBirth: new Date("2000-12-31T00:00:00.000Z"),
			nationality: "American",
		},
		{
			driverId: "stroll",
			permanentNumber: 18,
			code: "STR",
			url: "http://en.wikipedia.org/wiki/Lance_Stroll",
			givenName: "Lance",
			familyName: "Stroll",
			dateOfBirth: new Date("1998-10-29T00:00:00.000Z"),
			nationality: "Canadian",
		},
		{
			driverId: "tsunoda",
			permanentNumber: 22,
			code: "TSU",
			url: "http://en.wikipedia.org/wiki/Yuki_Tsunoda",
			givenName: "Yuki",
			familyName: "Tsunoda",
			dateOfBirth: new Date("2000-05-11T00:00:00.000Z"),
			nationality: "Japanese",
		},
		{
			driverId: "max_verstappen",
			permanentNumber: 33,
			code: "VER",
			url: "http://en.wikipedia.org/wiki/Max_Verstappen",
			givenName: "Max",
			familyName: "Verstappen",
			dateOfBirth: new Date("1997-09-30T00:00:00.000Z"),
			nationality: "Dutch",
		},
		{
			driverId: "zhou",
			permanentNumber: 24,
			code: "ZHO",
			url: "http://en.wikipedia.org/wiki/Guanyu_Zhou",
			givenName: "Guanyu",
			familyName: "Zhou",
			dateOfBirth: new Date("1999-05-30T00:00:00.000Z"),
			nationality: "Chinese",
		},
	]);
});
